"""empty message

Revision ID: 0751c5f4f08b
Revises: 0acf5d52b807
Create Date: 2025-05-30 16:54:24.459008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0751c5f4f08b'
down_revision = '0acf5d52b807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_pwd', sa.String(length=256), nullable=False))
        batch_op.drop_column('pwd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pwd', mysql.VARCHAR(length=256), nullable=False))
        batch_op.drop_column('_pwd')

    # ### end Alembic commands ###
